import addPathToString from './addPathToString';
import addEachDeep from './addEachDeep';
import addForEachDeep from './addForEachDeep';
import addIndex from './addIndex';
import addPaths from './addPaths';
import addKeysDeep from './addKeysDeep';
import addExists from './addExists';
import addCondense from './addCondense';
import addCondenseDeep from './addCondenseDeep';
import addFilterDeep from './addFilterDeep';
import addFindDeep from './addFindDeep';
import addFindPathDeep from './addFindPathDeep';
import addFindValueDeep from './addFindValueDeep';
import addOmitDeep from './addOmitDeep';
import addPickDeep from './addPickDeep';
import addObtain from './addObtain';
import addPathMatches from './addPathMatches';
import addReduceDeep from './addReduceDeep';
import addSomeDeep from './addSomeDeep';
import addMapDeep from './addMapDeep';

export default function apply(_) {
  addPathToString(_);
  addEachDeep(_);
  addForEachDeep(_);
  addIndex(_);
  addPaths(_);
  addKeysDeep(_);
  addExists(_);
  addCondense(_);
  addCondenseDeep(_);
  addFilterDeep(_);
  addFindPathDeep(_);
  addFindValueDeep(_);
  addFindDeep(_);
  addOmitDeep(_);
  addPickDeep(_);
  addObtain(_);
  addPathMatches(_);
  addReduceDeep(_);
  addSomeDeep(_);
  addMapDeep(_);
  return _;
}
